### ISSUE TITLE
Dashboard with Pull Requests across Organizations

### ISSUE THREAD

**Issue by maxandersen** [dennisreimann/ioctocat#164]
Would be great to see repos for organization sorted by the number of pullrequests that are open

**Comment by dennisreimann** [comment]
yep, that's definitely coming, though I can't give a date for that yet.

**Comment by dennisreimann** [comment]
I asked GitHub about an API endpoint for that, because right now this isn't available. Here's the answer:

> As a work around you can call one of the [List Issues methods](http://developer.github.com/v3/issues/#list-issues) and filter on the pull object on each item.
> Null urls for the pull mean it's not a pull request.

I suggest we wait some more to see whether or not they will properly solve this. I also talked to them about the Null URLs and these are supposed to be handled properly when API v3 is out of beta - so let's wait at least until then.
