### ISSUE TITLE
profile 

### ISSUE THREAD

**Issue by elvisimprsntr** [dennisreimann/ioctocat#169]
Add ability to edit profile and add picture for avatar

**Comment by dennisreimann** [comment]
Thanks for your feedback! There is a way to [edit user attributes via the API](http://developer.github.com/v3/users/#update-the-authenticated-user) (at least some of them), but do you think this is really neccessary from a mobile device? I'm asking because I'd like to keep the stuff out that's not occurring on a regular basis and I personally don't see a use case for this on my iPhone or iPad.

GitHub accesses avatars via Gravatar, so there is no other way to change your avatar than switching to another email address or updating the avatar at Gravatar itself.

**Comment by klaustopher** [comment]
And there are some Gravatar Apps out there on the app store
