### ISSUE TITLE
Quick next/prev browsing of commits

### ISSUE THREAD

**Issue by MadsBuus** [dennisreimann/ioctocat#173]
Still the best git app, thanks. 
My primary use case for ioctocat is quickly browsing commits on a project (especially peripheral projects I don't contribute to every day)

This has become even more frustrating is the latest versions: the news/activity views only shows type of action, who and where, but IMO should show the commit messages directly. When I click an entry it now just shows 4 buttons, I ALWAYS need to click the plus sign, then i can read parts of the commit messages, then click added/modified files, then click a specific file and finally a diff. The I have to go back 4 times, click the next row, and click 3 times to see commit messages, and 2 more for each file. This usability is very far from my use case. 

In my head the commit messages are the meat, secondly (if the commit message is interesting or confusing) the actual diffs). Going to the user, the organization or the repo in general is rarely used and could still be done with buttons. 

Regards
/Mads

**Comment by dennisreimann** [comment]
I am currently working on this.

**Comment by dennisreimann** [comment]
To clarify this a bit: Before the latest version, the events where coming from the atom feeds on GitHub. This brought some drawbacks with it, like requiring the user to enter the API token. With the v1.6.2 release I switched event retrieval to the GitHub API, which gives us much more flexibility for working with events. Nevertheless this was a very big switch and I had to rewrite a lot of code - that's why I seperated the tasks and focused on bringing the new event handling and UI out there first. 

I can understand that you don't like the current state and I also know some things beyond commits in the activity feed, that could be improved. Like I said I'm currently working on this and will release an update that brings commit messages, comments and repo descriptions to the extended view of an event. This will happen soon :)

**Comment by MadsBuus** [comment]
Hi Dennis
That sounds fantastic! In the projects I run, I really urge people to write good, short commit messages, so a list (short git log-style) of all commit messages in the push would be really helpful. I don't know if that info is even in the feeds, otherwise it will be pretty costly to retrieve for you, unless you actually do a kind of git fetch locally on the mobile device, keeping a local log  :-)

Thanks again for your great work. 
Regards,
Mads

**Comment by dennisreimann** [comment]
To give you an impression of how I imagine it, here's a screenshot of the current state:

![Commit Event](https://dl.dropbox.com/u/980580/Screenshots/ioctocat-events-01.png)

The commit button on the bottom right currently leads to the first commit. In case there is more than one commit it will bring you to a list of commits from which you can choose the specific commit. The list will also include the number of added, modified and deleted files. I'll work on that later today and post a screenshot once it is done.

**Comment by MadsBuus** [comment]
That looks fantastic and will help me a lot. I might prefer actually just clicking the actual commit message to go to that commit, but as long as flipping through each commit in a push is easy, It solves my use case. 

Thanks again for a great product.  
An idea for future feature: taking the ioctocat users last commit and showing everything since that date (a kind of mix of events with own activity), but the current sync works flawlessly.

**Comment by dennisreimann** [comment]
Can you please describe in more detail what you mean in the last paragraph? I didn't get it.

>  I might prefer actually just clicking the actual commit message to go to that commit

Unfortunately we cannot use links in this view as we are doing it in the repo or issue description, because it has some drawbacks like not being able to close the details view by clicking on any text that's not linked. Maybe I'll find a way around this, but the next release will likely look like what I described, because I want to get it out in the next days.

**Comment by dennisreimann** [comment]
I added the commits overview in 69f5965ba144518c0a8583a8f045355cdd4be8a4.

![Commits overview](https://dl.dropbox.com/u/980580/Screenshots/ioctocat-events-02.png)

I'll close this for now and will see, how it can be improved further.

**Comment by MadsBuus** [comment]
Ny hero. Looping forward to next release!
/Mads
