### ISSUE TITLE
Comments don't show linked issues/merges

### ISSUE THREAD

**Issue by benwoody** [dennisreimann/ioctocat#187]
Using Beta v1.6.5

As shown below, when there are links to a pull requests merge, it does not show the link to the pull request data.  As seen below, from https://github.com/benwoody/tpdata/pull/2

![photo](https://f.cloud.github.com/assets/625707/22983/d4bf337a-4a1c-11e2-86c8-9d30100b35ef.PNG)

However, if you then 'View on Github' and return, the Hash will show up in the comments with no clickable link.

**Comment by benwoody** [comment]
Actually, it seems if you scroll past the comment block that is missing text and then scroll back, the text appears.

**Comment by dennisreimann** [comment]
Yep, its a little more complicated. I'll tackle this together with Markdown parsing, because right now the text views just contain the raw text, in which links get parsed by the UITextView. 

Will be one of the next features I'll be working on, because I have this on the list for quite some time now and it will help us in other places too.

**Comment by iosdeveloper** [comment]
If raw output is shown I wonder why the text is disappearing then? Looks to me like a memory or cell reuse issue!? Please consider a bugfix before implementing markdown as it will take some time.

**Comment by dennisreimann** [comment]
I found the error, it is not related to links in the text. Its cause is, that the height of the UITextView which contains the text isn't set correctly - the cell has the correct height, but the inner text view is to small.

Will ship a fix in v1.7.7
