### ISSUE TITLE
Increase spacing between table cells

### ISSUE THREAD

**Issue by bushxnyc** [dennisreimann/ioctocat#198]
Would like to see the a redesign of the rest of the interface as well.

**Comment by dennisreimann** [comment]
Thanks! I'm working on it - what especially would you like to see improved?

**Comment by bushxnyc** [comment]
Well mostly I'd suggest working on the styling of the fonts and chrome for
the selection buttons like the list of repositories. At the moment they
kind of blend together.

**Comment by bushxnyc** [comment]
Also is there a way you could make the code display re-sizable?

**Comment by dennisreimann** [comment]
Actually I added resizing for the code view just yesterday, see  4c8eeecb1e7593739d9d1d7cbe201bc18902a562 :)

> I'd suggest working on the styling of the fonts and chrome for
> the selection buttons like the list of repositories. At the moment they
> kind of blend together.

What do you mean by that? I don't get it :)

**Comment by bushxnyc** [comment]
I just meant make the buttons like in the Personal view separate so it's
easier to distinguish one from the other. Such as the list of repos. I have
many that I track and the buttons to select them sort of blend together.
It's not a show stopper just a preference. Think of the keypad in IOS.
Separate distinct buttons. Something like that.

**Comment by dennisreimann** [comment]
You mean giving each cell in the repositories list a margin, so that there is space between each repo in the list?

**Comment by bushxnyc** [comment]
Yes. But the repo list was just an example you have several lists in the
app that have joined items. Again, just a suggestion.

**Comment by dennisreimann** [comment]
Ok, in 2495b9d8540622465a6d9e9dad79cb22d7aad125 I first of all separated out the watched and starred repos from the personal repos view, so that the personal view now only contains the private and public repos of the current user. 

I want to redesign the lists with grouped styles anyway, I'll take your suggestion into account and will see what I can do for you :)

![iOS Simulator Bildschirmfoto 05 01 2013 23 44 02](https://f.cloud.github.com/assets/886/45491/b5065dcc-5789-11e2-9fb8-6cfdddeb4e9e.png)
