### ISSUE TITLE
Repositories not loading

### ISSUE THREAD

**Issue by guidoscheffler** [dennisreimann/ioctocat#223]
I have four private and no public repos in my github account. I can access these repos via the activity feed, but the repositories view says I have no repositories.

**Comment by dennisreimann** [comment]
Hmmm, might be related to the fact, that there are no public repos, but even that would be weird. Does reloading the list help? If not, which version are you using - the one from the App Store or the current master here on GitHub?

**Comment by guidoscheffler** [comment]
I'm using the one from the app store. Reloading the list does not help; I also tried logging out and in again; closing the app via the multitasking bar and even reinstalling the app. The same problem occurs on my iPhone 5 and my iPad 3.

**Comment by dennisreimann** [comment]
Ok, I checked it, and for me it works with having only private repos, so that might not be the problem.

Do the repos appear on your profile page? If not, then there must be something wrong with the loading of the repos.

Out of curiosity: Can you add a bare public repo if you can' see any repos on your profile page?

**Comment by guidoscheffler** [comment]
I just added a public repo.
The profile page -as well as the repositories page- now show this repo, however, for the private repos it still shows "No private repositories".

**Comment by dennisreimann** [comment]
Hmm, I would have said that there must be something wrong with the OAuth scope for the private repo access - but I guess you would not be able to access the repos from the feed if that'd be the case. 

Nevertheless: can you try to go back to the accounts list, access your account this is happening with with the button on the right, enter your password and reauthenticate?

This will refresh the OAuth access token, I hope this helps, as I don't know what else could be the problem.

**Comment by guidoscheffler** [comment]
I just tried re-authenticating like you suggested, but my private repos are still not shown (I can, however, access them via the activity feed).
![ioctocat_repo_bug](https://f.cloud.github.com/assets/2256513/102755/780a847c-6939-11e2-9b40-41ab00f68d8c.png)

**Comment by dennisreimann** [comment]
Okay, so to debug this a little bit better I just pushed a [script to debug API responses](/dennisreimann/ioctocat/commit/78efa7cd58f9a1277a268998bebb8051af481e89). Can you please clone the repository and run this command:

```
Debug/api.rb user/repos guidoscheffler YOUR_PASSWORD
```

This will write a log file o the Debug diectory, cann you attach the output or send it to my email address? See [my profile](/dennisreimann) for the mail address.

**Comment by guidoscheffler** [comment]
Debug/api.rb:14:in `require': no such file to load -- json (LoadError)
    from Debug/api.rb:14
Sadly I have no ruby experience whatsoever (yet); do I have to install a json package or something?

**Comment by dennisreimann** [comment]
I guess you are running a ruby version that's pre-1.9. What does this command yield?

```
ruby -v
```

**Comment by guidoscheffler** [comment]
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by dennisreimann** [comment]
Okay, here we go: 74609e0b115e12a5fcf4ba54d89cbcc87443ca0d

Just install the json gem with `gem install json` - if this does not work, use `sudo gem install json`.

Please also update your local repo (because there needs to be a `require "rubygems"` in the script) and run this again:

```
Debug/api.rb user/repos guidoscheffler YOUR_PASSWORD
```

**Comment by guidoscheffler** [comment]
I've sent you an email with the log file.

**Comment by dennisreimann** [comment]
Thanks Guido, I received it and can verify your private repos are in the data that's coming back from the GitHub API. I'll have to investigate some more, because the two things I was suspecting to be wrong are likely not the case:
- You already reauthenticated, so it should not be a problem related to the OAuth scope (even though I can't completely verify that, because the ruby script authorizes via HTTP Basic Auth and not via OAuth like the app, but the response should be the same).
- It also should not be related to caching, because you reinstalled the app and it still didn't work afterwards.

I'm sorry that I don't have a solution for this at the moment, but as far as I know this is the first time something like that happens.

**Comment by guidoscheffler** [comment]
I just updated to 1.7.5 and now all repositories are shown on my profile page as well as on the dedicated repositories page :)
