### ISSUE TITLE
Show the Github OAuth Authorization Page

### ISSUE THREAD

**Issue by brndnblck** [dennisreimann/ioctocat#230]
Even if you're not collecting a password, putting your own UI over Github's authorization page defeats the purpose of using OAuth.

Part of the reason the spec requires authorization on the provider's end is so that users who are authenticating can know they're doing so against a trusted source.

I'm sure you did this to provide a less jarring and smoother login flow, but the tin foil hats amongst us won't be inclined to trust their credentials to a third party.

Additionally, the authorization page is there so that users can visibly see what permissions are bein granted to the API consumer (your app).

Without seeing the code and without seeing GH's authorization page I don't know what's being done with my password or what permissions I'm granting your app.

**Comment by dennisreimann** [comment]
I tried to do it like that when I initially implemented login via OAuth. I also talked to people at GitHub and the workflow for non-web apps seems to require authorization via the API, see this for details: http://developer.github.com/v3/oauth/#non-web-application-flow

Even if it would work for GitHub.com there'd still be a problem to make it work with Enterprise installations, because authorizing via the web app workflow requires a OAuth app to be in place at the Enterprise endpoint. There is no way iOctocat could know about the client_id of that app. 

I know this is kinda disappointing, but we'll have to live with that for now. I could list the requested scopes on the authentication view though.

**Comment by brndnblck** [comment]
ahhh, yeah. I hadn't thought about support for GH enterprise. That's kind of a monkey wrench in the whole workflow.

**Comment by dennisreimann** [comment]
nevertheless, I'll leave this open as it would be really nice to have a proper workflow for this.

**Comment by dennisreimann** [comment]
Here's some insight into how GitHub handles this in Octokit: octokit/octokit.objc#31

**Comment by dennisreimann** [comment]
I talked to GitHub numerous times about this. It isn't possible in our case.
