### ISSUE TITLE
Localization for iOctocat

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#271]
I know a lot of coders are international, so I think it would be really nice to have localization.  

Sidenote:  do you plan to open source the server when you complete the push notifications?  That'd be sweet.

Btw:  I found an app that was a complete copy of iOctocat on the App Store, thought I'd let you know. Esp. since iOctocat is open source.

**Comment by iosdeveloper** [comment]
I hope Apple removes those copy_cat_s sooner than later... Those people don't give back to the community by including proper attribution or commiting back their changes... Happened to the famous 'Canabalt' too and definitely hurts the open source community... Have you submitted a complaint yet?

**Comment by dennisreimann** [comment]
Localization: Won't do it. GitHub isn't localized, so this app won't be too, as it would be inconsistent anyways... all text coming from GitHub is in english.

Copycats: I submitted a complaint about "GitHub Mobile Edition", but it's complicated to sort out, because iOctocat is released under a MIT license. I don' wanna waste my precious time battling these people, I like to use the time to hack new features.
