### ISSUE TITLE
Settings: Disable avatar loading

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#276]

**Comment by MazyM** [comment]
May I ask what do you mean by "via Cellular only"?

**Comment by iosdeveloper** [comment]
Disable avatar loading via WWAN (LTE/4G/3G/EDGE) only.

**Comment by MazyM** [comment]
Thanks for your explanation. There is one thing which is not clear to me: how to arrange the Settings bundle so it is simple and intuitive for an user. 

My idea is following:
- rename "Avatar cache" group to "Avatar"
- rename switch "Clear on next launch" to "Clear cache"
- add new switch "Disable loading"
- add new switch "Cellular mode"

What do you think about it?

Edit: My idea is not very good. Imagine an user which wants to disable avatar loading because he is connected via 3G. He opens the Settings and there are two switches "Disable loading" and "Cellular mode", it might not be clear which switch should be switched on (Celluar mode OR Disable loading or BOTH?).

**Comment by iosdeveloper** [comment]
Maybe use multivalue instead of toggle switch?

**Comment by iosdeveloper** [comment]
A single switch to disable avatar loading in general should do to avoid confusion. What do you think?

**Comment by iosdeveloper** [comment]
We would not need additional source like Reachability if we use a single switch, I would prefer it that way for now.

**Comment by iosdeveloper** [comment]
Closed by 4ec69df
