### ISSUE TITLE
Sometimes the 'Add comment' button is not displayed at all

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#301]
Screenshot:
![image](https://f.cloud.github.com/assets/655921/179490/cb37d5f8-7c00-11e2-8511-a2c5c133694d.jpg)

**Comment by iosdeveloper** [comment]
Still occurs in v1.7.7.1. Reopening...

**Comment by dennisreimann** [comment]
I tried various things and none of them are working the way I'd like. It all sems to come down to that the tableViewFooter the button is in does not seem to play nice with reloadSections. Let's just fall back to using reload data [instead of reloadSections](/dennisreimann/ioctocat/blob/master/Classes/IOCIssueController.m#L142) - what do you think @iosdeveloper ? That'd also simplify the code a bit (but would not look as nice, as the changes won't be animated)

**Comment by iosdeveloper** [comment]
Maybe embedding the button in an `UIView` and setting the correct autosizing masks will do the trick!?

**Comment by dennisreimann** [comment]
That's how it (not ;)) works currently.

**Comment by iosdeveloper** [comment]
What about setting `tableFooterView` instead of the footer of a separate section?

**Comment by dennisreimann** [comment]
That might work, that's how it has been previously - I changed it to be a section footer when I added the merge pull feature, because I needed a section footer for that.

Ok, I'll change this for the next beta and if it does not work out, we'll simply reloadData.

**Comment by dennisreimann** [comment]
Don't dare to reopen, @iosdeveloper :tongue:
