### ISSUE TITLE
Gists: Check updated date

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#316]
https://gist.github.com/adamgit/3705459

Last edit/comment: 2 months ago

In iOctocat:

> Updated: 1 day ago

**Comment by dennisreimann** [comment]
Seems that GitHub counts in comments as well, when displaying the date in the header - in this screenshot the last comment was made 2 two months ago.

![Bildschirmfoto 2013-02-25 um 16 46 17](https://f.cloud.github.com/assets/886/192428/95020a02-7f62-11e2-8a7e-818183c403a9.png)

The date fields returned from the API for this gist look like this:

```
    "created_at" = "2012-09-12T09:15:02Z";
    "updated_at" = "2013-02-25T15:43:15Z";
```

This looks a bit messed up, because the updated_at field seems to reflects the date and time of the request/response?!

However: The last [revision of this gist](https://gist.github.com/adamgit/3705459/revisions) is also two months ago, but that occurs nowhere in the API response. I'll take a closer look at other gists.

**Comment by dennisreimann** [comment]
Current state: I sent an email to GitHub about this and they will investigate and see what can be done to provide a date that reflects the updates on the actual gist. 

One more thing: I was wrong when saying the updated_at was the date and time of the request/response - it is the date of the latest action performed on that gist: me starring it. (which occured some seconds before the request)

So to make it clear: The updated_at value coming from the API currently reflects the date and time of the latest action on the gist and it's associated items, like stars, comments, etc.
