### ISSUE TITLE
Create pull requests

### ISSUE THREAD

**Issue by phillipthelen** [dennisreimann/ioctocat#340]
It would be nice if one could also create pull requests in addition to viewing and merging them.

**Comment by dennisreimann** [comment]
The API [supports this](http://developer.github.com/v3/pulls/#create-a-pull-request), nevertheless I find the workflow a bit strange, because there is no way to edit oder push code - so you'd have to do this on a different device (or in another app) and then create the pull request in iOctocat. I'll close it for now, because this has been the only request for the feature since the app exists - we'll work out the best way to do this once more people ask for this feature.

**Comment by hannahjherself** [comment]
I would also like to be able to create pull requests in iOctocat. I can commit and push changes to my own forked repositories in Working Copy and also merge upstream changes but I have no way of generating a pull request to get the changes in my forked repo upstream. Right now I have to login to GitHub on my browser and generate the pull request there. Creating pull requests in iOctocat would put all of the upstream management in the one place.
