### ISSUE TITLE
Strip emails

### ISSUE THREAD

**Issue by dignifiedquire** [dennisreimann/ioctocat#413]
When displaying issue comments that were answered per email it would be nice to hide/strip the "old" part of the email that you can already see in the comments before. Similar to how it happens on Github itself

![screen shot 2013-08-17 at 9 14 40 pm](https://f.cloud.github.com/assets/790842/981579/501cdc2c-0771-11e3-834a-1810580e080b.png)

**Comment by dennisreimann** [comment]
Hello and thanks for the feedback. That is already implemented in v2 of iOctocat - I guess you are using v1.8.x, right?

**Comment by dignifiedquire** [comment]
Nope using v2 :( but had quite a few issues were the complete history was shown

**Comment by dennisreimann** [comment]
v2.0.1 is already in review and I fixed a few things concerning Markdown and email footer parsing. Can you point me to the actual examples - ideally by posting the iOctocat URLs (with ioc:// instead of https:// - like ioc://github.com/dennisreimann/ioctocat/issues/413 for this issue) so that I can verify I cover all cases?

There are some weird syntax differences in the mail footers, but v2.0.1 should already cover what I've come across so far. 

Thanks!

**Comment by dignifiedquire** [comment]
Alright will wait for v2.0.1, test again and post if the issue persists.

**Comment by dignifiedquire** [comment]
Seems to be fixed :)
