### ISSUE TITLE
Badge icon will not reset

### ISSUE THREAD

**Issue by OliverJAsh** [dennisreimann/ioctocat#418]
The badge that sits on top of the iOctocat icon and counts the number of notifications is gradually increasing. When I mark all notifications as read, the badge disappears, only to appear again a few minutes later with the same number.

I.e:

"65 notifications"
_Marks as read, closes the app._
A few minutes later after receiving two new notifications: "67 notifications"

I am running iOS 7.

**Comment by dennisreimann** [comment]
v2.1.0 is supposed to ship today and is iOS 7 compatible. Please check whether or not the new version fixes this for you.

**Comment by OliverJAsh** [comment]
OK. Will report back when the update comes through.

**Comment by OliverJAsh** [comment]
I'm still having this issue after the update.

![](http://cl.ly/image/3t0x1w3W1l3F/content)

**Comment by dennisreimann** [comment]
Ok, thanks! You don't seeem to be the only one experiencing this - I'll have a closer look!

**Comment by dennisreimann** [comment]
Can you tell me, whether or not you had the app on your device before upgrading to iOS 7?
I think I might know what's going on...

**Comment by OliverJAsh** [comment]
I did, yes!

**Comment by dennisreimann** [comment]
Alright, then please just deactivate and reactivate the push feature in the account settings.

I noticed for myself that the device identifier of my phone changed when I upgraded to iOS 7 and do not have the problem, because I did a fresh install and hence the server knows the new identifier. By reenabling push, the server will receive your current (potentially new) device identifier and the problem should go away.

Can you do that and let me know tomorrow whether or not this helped?

**Comment by dennisreimann** [comment]
@OliverJAsh Did you check if this works for you?

**Comment by OliverJAsh** [comment]
Yes, sorry. Seems to have fixed it! Thank you.

**Comment by dennisreimann** [comment]
Alright, thanks for your answer :)
