### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by capnslipp** [dennisreimann/ioctocat#48]
I don't see this already on here, so I might as well add it. Push notifications would be great.

I find I don't actually use a lot of apps I have that don't have push notifications; this being one of them. Sure, it provides an optimized view of GitHub that loads faster. Sure, I can check it at a glance on-the-go. In reality, most of the time I'm sitting at a computer with a full web browser or I have decent 3G coverage and I can just pull up "http://github.com/..." itself.

Push notifications would bring this app into common usage on my iPhone; when something happens that I want to know about, I get to know instantly. I'm no psychologist, but it's a sort of game to me (and I assume others): if it's fresh and new and I'm the first to know, it's exciting.

I'm no expert in the technology, but I believe push notifications require somebody's server to poll github.com for changes and send the notifications to the devices… hardly affordable to include in a free app. If this is so, I can think of a few solutions:
1. Build a simple open-source desktop daemon that watches GitHub and sends out push notifications to the iPhone of your choice.
2. Same as 1, but simply provide Growl notifications; these can be routed to an iPhone via Prowl.
3. Partner/tie into of the push notification services (like Boxcar); this way they handle the cost of watching GitHub and sending notifications to devices.
4. Convince GitHub to do it. ;-D

**Comment by jk** [comment]
You're right, since GitHub doesn't do the job in running a daemon that pushes to Apples Push Server somebody else have to run it. But in my understanding of the APNS (Apple Push Notification System) only the developer of the app can run the service which communicates with the APNS because of the code signing, which Apple requires.

So it's down to Prowl and Boxcar… which isn't a very convenient way to do it, especially for the end user, IMO.

But maybe you spend dbloete some money so he can pay regular support payments of such a service :-)

**Comment by capnslipp** [comment]
Hmm. Not a bad idea. Somebody could run a push server based on donations; when there are enough donations, we have push; when there aren't, no push.

If one purchased hosting for **just** iOctocat push notifications, how much servering power would it require?

Would $10/month for cheap hosting work? I would think it would be quite easy to pay for that in donations.

Would $50-100/month for slice hosting work? A bit harder to swallow, but only Dennis Blöte knows how many people are using the app and how much money $5/year from 1% of the users would be.

**Comment by dennisreimann** [comment]
Try using Eventbox/Socialite Feeds and Prowl for that - it works fine for me, but I'm not a big fan of push notification, anyway... I'd be annoyed to be updated about every commit to some repo, but maybe it's just me ;)

I'm closing this ticket because I don't have the time and resources to feature a push notification service.

**Comment by capnslipp** [comment]
Sure sure. Didn't know if you had a way to classify it "wish list" or not. Thanks for the suggestion!
