### ISSUE TITLE
Rewrite the app using Three20 library

### ISSUE THREAD

**Issue by dima767** [dennisreimann/ioctocat#50]
http://wiki.github.com/joehewitt/three20

Would serve as a really, really nice real-world example of using the library. Might not be doable nor desirable from the point of view of developres, but I thought I'd throw it out there anyway :-)

**Comment by dennisreimann** [comment]
This issue doesn't really make sense, because there would be no business value in rewriting the app just for the purpose of using an other nice library... however: Some ideas regarding the use of Three20 for future versons have accumulated in the wiki, see: http://wiki.github.com/dbloete/ioctocat/version-20-proposal
